export type TrueFalseQuestion = {
  id: string
  unit: number
  statement: string
  answer: boolean
  explanation: string
}

export type ChoiceQuestion = {
  id: string
  unit: number
  question: string
  options: string[]
  answerIndex: number
  explanation: string
}

export type ShortAnswerQuestion = {
  id: string
  unit: number
  question: string
  answer: string
}

export const trueFalseQuestions: TrueFalseQuestion[] = [
  {
    id: "tf1",
    unit: 1,
    statement: "The kernel is the core part of the OS that runs at all times.",
    answer: true,
    explanation:
      "The kernel runs continuously and handles memory management, process management, and device control.",
  },
  {
    id: "tf2",
    unit: 1,
    statement: "A system call is a hardware interrupt generated by a peripheral device.",
    answer: false,
    explanation:
      "A system call is the software interface between a user program and the OS. (A software interrupt/trap is used to enter the kernel, but the system call itself is not a hardware interrupt.)",
  },
  {
    id: "tf3",
    unit: 1,
    statement: "In dual-mode operation, privileged instructions can only be executed in kernel mode.",
    answer: true,
    explanation:
      "Privileged instructions are restricted to kernel mode; attempting them in user mode causes a trap to the OS.",
  },
  {
    id: "tf4",
    unit: 1,
    statement: "A multiprocessor system uses a single CPU shared in time slices.",
    answer: false,
    explanation:
      "Multiprocessor (parallel) systems have two or more physical CPUs. Time-slicing a single CPU is multiprogramming/time-sharing.",
  },
  {
    id: "tf5",
    unit: 2,
    statement: "Threads within the same process share the code and data sections.",
    answer: true,
    explanation:
      "Threads share the code, data, and OS resources but each has its own program counter, stack, and registers.",
  },
  {
    id: "tf6",
    unit: 2,
    statement: "Context switching performs useful computational work for the running process.",
    answer: false,
    explanation:
      "Context switching is pure overhead — it does no useful work. Frequent switching reduces performance.",
  },
  {
    id: "tf7",
    unit: 2,
    statement: "A zombie process is one that has terminated but whose entry still remains in the process table.",
    answer: true,
    explanation:
      "A zombie has finished execution but its PCB entry remains until the parent reads its exit status (wait).",
  },
  {
    id: "tf8",
    unit: 2,
    statement: "The fork() system call returns the same value to both parent and child.",
    answer: false,
    explanation:
      "fork() returns the child's PID to the parent and 0 to the child, so they can distinguish their roles.",
  },
  {
    id: "tf9",
    unit: 3,
    statement: "Round Robin scheduling is a preemptive algorithm that prevents starvation.",
    answer: true,
    explanation:
      "RR gives each process a fixed time quantum and cycles through the ready queue, so every process gets the CPU — no starvation.",
  },
  {
    id: "tf10",
    unit: 3,
    statement: "FCFS scheduling generally produces the lowest average waiting time of all algorithms.",
    answer: false,
    explanation:
      "FCFS suffers the convoy effect and has high average waiting time. SJF is optimal for minimizing average waiting time.",
  },
  {
    id: "tf11",
    unit: 3,
    statement: "Shortest Job First scheduling is provably optimal for minimizing average waiting time.",
    answer: true,
    explanation:
      "SJF gives the minimum average waiting time for a given set of processes, but requires knowing burst lengths in advance.",
  },
  {
    id: "tf12",
    unit: 3,
    statement: "A very small time quantum in Round Robin eliminates context-switch overhead.",
    answer: false,
    explanation:
      "A very small quantum increases the number of context switches, raising overhead. Too large a quantum degrades RR to FCFS.",
  },
  {
    id: "tf13",
    unit: 4,
    statement: "All four Coffman conditions must hold simultaneously for a deadlock to occur.",
    answer: true,
    explanation:
      "Mutual exclusion, hold and wait, no preemption, and circular wait must all hold for deadlock.",
  },
  {
    id: "tf14",
    unit: 4,
    statement: "A race condition occurs when the outcome depends on the relative timing of processes.",
    answer: true,
    explanation:
      "A race condition arises when multiple processes access shared data concurrently and the result depends on execution order.",
  },
  {
    id: "tf15",
    unit: 4,
    statement: "The Banker's Algorithm detects deadlocks after they have already occurred.",
    answer: false,
    explanation:
      "The Banker's Algorithm is a deadlock avoidance method — it only grants requests that keep the system in a safe state.",
  },
  {
    id: "tf16",
    unit: 4,
    statement: "A binary semaphore can be used to provide mutual exclusion.",
    answer: true,
    explanation:
      "A binary semaphore takes values 0 and 1 and behaves like a mutex lock guarding a critical section.",
  },
  {
    id: "tf17",
    unit: 5,
    statement: "Paging eliminates external fragmentation but can cause internal fragmentation.",
    answer: true,
    explanation:
      "Fixed-size frames remove external fragmentation; the last frame of a process may be partly unused (internal fragmentation).",
  },
  {
    id: "tf18",
    unit: 5,
    statement: "The Optimal page replacement algorithm can be implemented in real systems.",
    answer: false,
    explanation:
      "OPT requires knowledge of future references, so it is not implementable; it is used only as a benchmark.",
  },
  {
    id: "tf19",
    unit: 5,
    statement: "Thrashing occurs when a process spends more time paging than executing.",
    answer: true,
    explanation:
      "Thrashing is high paging activity caused by too few frames per process, severely reducing CPU utilization.",
  },
  {
    id: "tf20",
    unit: 5,
    statement: "The LRU algorithm suffers from Belady's anomaly.",
    answer: false,
    explanation:
      "LRU is a stack algorithm and does not suffer from Belady's anomaly. FIFO can suffer from it.",
  },
  {
    id: "tf21",
    unit: 5,
    statement: "Segmentation divides a process into variable-sized logical units.",
    answer: true,
    explanation:
      "Segmentation uses variable-sized segments matching logical divisions (code, stack, data), unlike fixed-size paging.",
  },
  {
    id: "tf22",
    unit: 6,
    statement: "SSTF disk scheduling can cause starvation of some requests.",
    answer: true,
    explanation:
      "SSTF always serves the nearest request, so requests far from the head can be starved if closer ones keep arriving.",
  },
  {
    id: "tf23",
    unit: 6,
    statement: "Contiguous file allocation makes it easy to grow a file over time.",
    answer: false,
    explanation:
      "Contiguous allocation makes growth hard — there may be no free blocks adjacent to the file, and it causes external fragmentation.",
  },
  {
    id: "tf24",
    unit: 6,
    statement: "A file's logical structure is independent of how it is physically stored on disk.",
    answer: true,
    explanation:
      "The logical view (records, byte stream) is separate from the physical allocation method on the storage device.",
  },
  {
    id: "tf25",
    unit: 6,
    statement: "Seek time is the time required for the desired sector to rotate under the read/write head.",
    answer: false,
    explanation:
      "Seek time is moving the head to the correct track. Rotational latency is the time for the sector to rotate under the head.",
  },
  {
    id: "tf26",
    unit: 7,
    statement: "DMA allows data to be transferred between a device and memory without per-byte CPU involvement.",
    answer: true,
    explanation:
      "The DMA controller transfers entire blocks independently and raises a single interrupt when done.",
  },
  {
    id: "tf27",
    unit: 7,
    statement: "Programmed I/O (polling) keeps the CPU busy checking device status repeatedly.",
    answer: true,
    explanation:
      "In programmed I/O the CPU continuously polls the status register, wasting cycles while waiting.",
  },
  {
    id: "tf28",
    unit: 7,
    statement: "A device driver is hardware that physically controls a peripheral device.",
    answer: false,
    explanation:
      "A device driver is software — it provides a uniform interface to the kernel and translates requests for a specific device.",
  },
  {
    id: "tf29",
    unit: 7,
    statement: "Spooling allows a slow device such as a printer to be shared among many processes.",
    answer: true,
    explanation:
      "Spooling queues output on disk so multiple processes can submit jobs that are printed one at a time.",
  },
  {
    id: "tf30",
    unit: 1,
    statement: "An operating system acts as an intermediary between the user and the computer hardware.",
    answer: true,
    explanation:
      "The OS sits between applications/users and hardware, managing resources and providing services.",
  },
  {
    id: "tf31",
    unit: 2,
    statement: "Cooperating processes can affect or be affected by other processes in the system.",
    answer: true,
    explanation:
      "Cooperating processes share data or communicate, so they can influence each other (unlike independent processes).",
  },
  {
    id: "tf32",
    unit: 3,
    statement: "Turnaround time is the total time from process arrival to its completion.",
    answer: true,
    explanation:
      "Turnaround time = completion time − arrival time, covering both waiting and execution.",
  },
  {
    id: "tf33",
    unit: 4,
    statement: "Removing the circular-wait condition is one way to prevent deadlock.",
    answer: true,
    explanation:
      "Imposing a total ordering on resource acquisition prevents circular wait and thus deadlock.",
  },
  {
    id: "tf34",
    unit: 5,
    statement: "The TLB is a fast cache that stores recent page-to-frame translations.",
    answer: true,
    explanation:
      "The Translation Lookaside Buffer caches recent translations to avoid slow page-table lookups in memory.",
  },
  {
    id: "tf35",
    unit: 6,
    statement: "In indexed allocation, one index block holds pointers to all of a file's data blocks.",
    answer: true,
    explanation:
      "Indexed allocation gathers all block pointers into an index block, supporting fast direct access without external fragmentation.",
  },
]

export const choiceQuestions: ChoiceQuestion[] = [
  {
    id: "mc1",
    unit: 1,
    question: "The core part of the operating system is called the:",
    options: ["Compiler", "Kernel", "BIOS", "Loader"],
    answerIndex: 1,
    explanation: "The kernel is the central component that always runs and manages core resources.",
  },
  {
    id: "mc2",
    unit: 1,
    question: "A system call is:",
    options: [
      "A hardware interrupt",
      "An application program",
      "The interface between a user program and the OS",
      "A scheduling algorithm",
    ],
    answerIndex: 2,
    explanation: "System calls are the API to the kernel used by user programs.",
  },
  {
    id: "mc3",
    unit: 1,
    question: "Which OS type guarantees a deterministic response time?",
    options: ["Batch", "Time-sharing", "Real-time", "Distributed"],
    answerIndex: 2,
    explanation: "Real-time operating systems provide deterministic (bounded) response times.",
  },
  {
    id: "mc4",
    unit: 1,
    question: "A microkernel architecture:",
    options: [
      "Includes all services in the kernel",
      "Minimizes kernel size by moving services to user space",
      "Has no inter-process communication",
      "Is considered outdated and unused",
    ],
    answerIndex: 1,
    explanation: "Microkernels keep only essentials in the kernel; other services run as user processes.",
  },
  {
    id: "mc5",
    unit: 1,
    question: "The transition from user mode to kernel mode is triggered by:",
    options: ["A normal arithmetic instruction", "A system call, interrupt, or trap", "Closing a file", "Loading a program"],
    answerIndex: 1,
    explanation: "System calls, hardware interrupts, and traps switch the CPU from user mode to kernel mode.",
  },
  {
    id: "mc6",
    unit: 1,
    question: "Which of the following is NOT a typical function of an operating system?",
    options: ["Process management", "Memory management", "Compiling source code into machine code", "File management"],
    answerIndex: 2,
    explanation: "Compilation is done by a compiler, not the OS. The OS manages processes, memory, files, and I/O.",
  },
  {
    id: "mc7",
    unit: 2,
    question: "A process is:",
    options: ["A program file", "A program in execution", "A compiler", "A type of thread library"],
    answerIndex: 1,
    explanation: "A process is a program in execution, including its code, data, stack, and registers.",
  },
  {
    id: "mc8",
    unit: 2,
    question: "The PCB (Process Control Block) stores:",
    options: ["Only the PID", "Only memory info", "All process information", "Compiler details"],
    answerIndex: 2,
    explanation: "The PCB holds PID, state, program counter, registers, scheduling, memory, and I/O info.",
  },
  {
    id: "mc9",
    unit: 2,
    question: "The short-term scheduler selects:",
    options: [
      "Jobs from disk to load into memory",
      "A process from the ready queue to run next",
      "An I/O device to use",
      "Which file to open",
    ],
    answerIndex: 1,
    explanation: "The short-term (CPU) scheduler picks which ready process gets the CPU next.",
  },
  {
    id: "mc10",
    unit: 2,
    question: "The Many-to-One thread model maps:",
    options: [
      "One user thread to many kernel threads",
      "Many user threads to one kernel thread",
      "Many kernel threads to many user threads",
      "One user thread to one kernel thread",
    ],
    answerIndex: 1,
    explanation: "Many user-level threads map onto a single kernel thread; one blocking call blocks all.",
  },
  {
    id: "mc11",
    unit: 2,
    question: "Which of these does a thread NOT have its own copy of?",
    options: ["Program counter", "Register set", "Stack", "Code section"],
    answerIndex: 3,
    explanation: "Threads share the code (text) section; each has its own PC, registers, and stack.",
  },
  {
    id: "mc12",
    unit: 2,
    question: "When a process is waiting for I/O to complete it is in the:",
    options: ["Running state", "Ready state", "Waiting/Blocked state", "New state"],
    answerIndex: 2,
    explanation: "A process waiting for an event such as I/O completion is in the waiting (blocked) state.",
  },
  {
    id: "mc13",
    unit: 3,
    question: "Which scheduling algorithm is most likely to cause the convoy effect?",
    options: ["Round Robin", "Shortest Job First", "First-Come, First-Served", "Priority Scheduling"],
    answerIndex: 2,
    explanation: "In FCFS, short processes wait behind long ones — the convoy effect.",
  },
  {
    id: "mc14",
    unit: 3,
    question: "Which scheduling algorithm is specifically designed for time-sharing systems?",
    options: ["FCFS", "SJF", "Round Robin", "Priority"],
    answerIndex: 2,
    explanation: "Round Robin's time quantum gives fair, responsive sharing among interactive users.",
  },
  {
    id: "mc15",
    unit: 3,
    question: "The time from process submission to the first CPU response is called:",
    options: ["Waiting time", "Turnaround time", "Response time", "Burst time"],
    answerIndex: 2,
    explanation: "Response time = first start time − arrival time.",
  },
  {
    id: "mc16",
    unit: 3,
    question: "Which scheduling algorithm can cause starvation of low-priority processes?",
    options: ["Round Robin", "FCFS", "Priority Scheduling", "First-In First-Out"],
    answerIndex: 2,
    explanation: "Priority scheduling can starve low-priority processes; aging solves it.",
  },
  {
    id: "mc17",
    unit: 3,
    question: "The preemptive version of Shortest Job First is called:",
    options: ["Round Robin", "Shortest Remaining Time First", "Highest Response Ratio Next", "Multilevel Queue"],
    answerIndex: 1,
    explanation: "SRTF preempts the running process if a newly arrived process has a shorter remaining burst.",
  },
  {
    id: "mc18",
    unit: 3,
    question: "CPU utilization is best defined as:",
    options: [
      "The number of processes completed per unit time",
      "The fraction of time the CPU is kept busy",
      "The time a process waits in the ready queue",
      "The total execution time of a process",
    ],
    answerIndex: 1,
    explanation: "CPU utilization is the percentage of time the CPU is actively doing work.",
  },
  {
    id: "mc19",
    unit: 4,
    question: "Which is NOT one of the requirements for a correct critical-section solution?",
    options: ["Mutual Exclusion", "Progress", "Bounded Waiting", "Preemption"],
    answerIndex: 3,
    explanation: "The three requirements are mutual exclusion, progress, and bounded waiting.",
  },
  {
    id: "mc20",
    unit: 4,
    question: "The Banker's Algorithm is used for deadlock:",
    options: ["Prevention", "Avoidance", "Detection", "Recovery"],
    answerIndex: 1,
    explanation: "It avoids deadlock by granting requests only if the system stays in a safe state.",
  },
  {
    id: "mc21",
    unit: 4,
    question: "A counting semaphore is most useful for:",
    options: [
      "Enforcing a single critical section only",
      "Managing multiple instances of a resource",
      "Replacing the kernel scheduler",
      "Preventing all interrupts",
    ],
    answerIndex: 1,
    explanation: "Counting semaphores track multiple available resource instances.",
  },
  {
    id: "mc22",
    unit: 4,
    question: "Which condition states that resources cannot be forcibly taken from a process?",
    options: ["Mutual exclusion", "Hold and wait", "No preemption", "Circular wait"],
    answerIndex: 2,
    explanation: "The no-preemption condition means a resource is released only voluntarily by the holding process.",
  },
  {
    id: "mc23",
    unit: 4,
    question: "The classic problem involving a buffer shared between a producer and consumer is the:",
    options: ["Dining Philosophers problem", "Readers-Writers problem", "Bounded-Buffer problem", "Sleeping Barber problem"],
    answerIndex: 2,
    explanation: "The bounded-buffer (producer-consumer) problem coordinates filling and emptying a shared finite buffer.",
  },
  {
    id: "mc24",
    unit: 4,
    question: "The wait() operation on a semaphore:",
    options: [
      "Increments the semaphore value",
      "Decrements the value and may block the process",
      "Always terminates the process",
      "Disables interrupts permanently",
    ],
    answerIndex: 1,
    explanation: "wait() (P) decrements the semaphore; if it becomes negative, the process blocks.",
  },
  {
    id: "mc25",
    unit: 5,
    question: "Which page replacement algorithm may suffer from Belady's anomaly?",
    options: ["LRU", "Optimal", "FIFO", "LFU"],
    answerIndex: 2,
    explanation: "FIFO can produce more page faults when more frames are added — Belady's anomaly.",
  },
  {
    id: "mc26",
    unit: 5,
    question: "The hardware cache that stores recent page-to-frame mappings is the:",
    options: ["MMU", "TLB", "PCB", "DMA controller"],
    answerIndex: 1,
    explanation: "The Translation Lookaside Buffer (TLB) caches recent address translations.",
  },
  {
    id: "mc27",
    unit: 5,
    question: "A logical address generated by the CPU is also called a:",
    options: ["Physical address", "Virtual address", "Frame number", "Bus address"],
    answerIndex: 1,
    explanation: "The CPU generates logical (virtual) addresses, which the MMU maps to physical addresses.",
  },
  {
    id: "mc28",
    unit: 5,
    question: "Internal fragmentation occurs when:",
    options: [
      "Free memory is scattered in small non-contiguous holes",
      "Allocated memory is larger than what the process requested",
      "A page is not found in memory",
      "Two processes share the same frame",
    ],
    answerIndex: 1,
    explanation: "Internal fragmentation is wasted space inside an allocated block (e.g., partly used last page).",
  },
  {
    id: "mc29",
    unit: 5,
    question: "Demand paging loads a page into memory:",
    options: ["At process creation", "Only when it is referenced", "When the disk is idle", "When the TLB is full"],
    answerIndex: 1,
    explanation: "Demand paging brings in a page lazily — only when the process actually references it.",
  },
  {
    id: "mc30",
    unit: 6,
    question: 'The disk scheduling algorithm also known as the "elevator algorithm" is:',
    options: ["FCFS", "SSTF", "SCAN", "C-LOOK"],
    answerIndex: 2,
    explanation: "SCAN moves the head in one direction servicing requests, then reverses — like an elevator.",
  },
  {
    id: "mc31",
    unit: 6,
    question: "Which file allocation method stores files in consecutive blocks?",
    options: ["Linked", "Indexed", "Contiguous", "Hashed"],
    answerIndex: 2,
    explanation: "Contiguous allocation uses consecutive blocks — fast access but external fragmentation.",
  },
  {
    id: "mc32",
    unit: 6,
    question: "Which disk scheduling algorithm services the request closest to the current head position?",
    options: ["FCFS", "SSTF", "SCAN", "C-SCAN"],
    answerIndex: 1,
    explanation: "SSTF (Shortest Seek Time First) selects the request with the minimum seek distance from the head.",
  },
  {
    id: "mc33",
    unit: 6,
    question: "A major disadvantage of linked file allocation is:",
    options: [
      "External fragmentation",
      "Poor performance for direct (random) access",
      "Inability to grow files",
      "Large internal fragmentation",
    ],
    answerIndex: 1,
    explanation: "Linked allocation supports only efficient sequential access; random access must follow pointers from the start.",
  },
  {
    id: "mc34",
    unit: 6,
    question: "The total time to access a disk block is approximately:",
    options: [
      "Seek time only",
      "Rotational latency only",
      "Seek time + rotational latency + transfer time",
      "Transfer time only",
    ],
    answerIndex: 2,
    explanation: "Disk access time = seek time + rotational latency + data transfer time.",
  },
  {
    id: "mc35",
    unit: 7,
    question: "Storing printer output on disk and printing it in the background is called:",
    options: ["Caching", "Spooling", "Buffering", "Swapping"],
    answerIndex: 1,
    explanation: "Spooling uses disk as intermediate storage to serialize output to slow devices.",
  },
  {
    id: "mc36",
    unit: 7,
    question: "DMA is used primarily to:",
    options: [
      "Increase the CPU clock speed",
      "Transfer data between device and memory without constant CPU involvement",
      "Replace the device driver",
      "Schedule processes",
    ],
    answerIndex: 1,
    explanation: "Direct Memory Access offloads bulk data transfer from the CPU, which is interrupted only when done.",
  },
  {
    id: "mc37",
    unit: 7,
    question: "The software that translates OS requests into device-specific commands is the:",
    options: ["Kernel scheduler", "Device driver", "Bootloader", "File system"],
    answerIndex: 1,
    explanation: "A device driver provides a standard interface to the kernel and controls a specific device.",
  },
  {
    id: "mc38",
    unit: 7,
    question: "Which I/O technique wastes CPU cycles by repeatedly checking a device's status?",
    options: ["Interrupt-driven I/O", "DMA", "Programmed I/O (polling)", "Memory-mapped I/O"],
    answerIndex: 2,
    explanation: "Programmed I/O (busy-wait polling) keeps the CPU looping on the status register until the device is ready.",
  },
  {
    id: "mc39",
    unit: 7,
    question: "Keeping copies of frequently accessed data in faster storage for reuse is called:",
    options: ["Spooling", "Buffering", "Caching", "Paging"],
    answerIndex: 2,
    explanation: "Caching stores frequently used data closer/faster to reduce repeated slow accesses.",
  },
  {
    id: "mc40",
    unit: 1,
    question: "Which of the following best describes multiprogramming?",
    options: [
      "Running several CPUs in parallel",
      "Keeping multiple jobs in memory so the CPU always has work",
      "Splitting one program across many computers",
      "Executing instructions out of order",
    ],
    answerIndex: 1,
    explanation: "Multiprogramming keeps several jobs in memory and switches the CPU to another when one waits, maximizing utilization.",
  },
]

export const shortAnswerQuestions: ShortAnswerQuestion[] = [
  {
    id: "sa1",
    unit: 1,
    question: "Define an operating system.",
    answer:
      "An operating system is system software that manages a computer's hardware and provides services for application programs, acting as an intermediary between users and hardware. It is a resource allocator and a control program.",
  },
  {
    id: "sa2",
    unit: 1,
    question: "List and explain three objectives of an OS.",
    answer:
      "Convenience — make the system easier to use. Efficiency/performance — use hardware resources effectively. Resource allocation — manage CPU time, memory, storage, and I/O devices. (Also protection & security.)",
  },
  {
    id: "sa3",
    unit: 1,
    question: "Differentiate between batch and time-sharing operating systems.",
    answer:
      "A batch OS groups jobs and processes them without user interaction (early mainframes). A time-sharing OS lets multiple users share the system simultaneously using small time slices (quanta), allowing interactive computing.",
  },
  {
    id: "sa4",
    unit: 1,
    question: "Explain the difference between mechanism and policy in OS design.",
    answer:
      "Policy is WHAT should be done (e.g. 'give the CPU to the highest-priority process'). Mechanism is HOW to do it (e.g. 'use a timer interrupt to regain control'). Keeping them separate lets you change policy without rewriting the mechanism.",
  },
  {
    id: "sa5",
    unit: 1,
    question: "What is dual-mode operation and why is it needed?",
    answer:
      "Dual-mode operation provides user mode and kernel mode, distinguished by a mode bit. Privileged instructions run only in kernel mode. It protects the OS and other processes by preventing user programs from directly executing dangerous operations.",
  },
  {
    id: "sa6",
    unit: 2,
    question: "Define a process and explain its components.",
    answer:
      "A process is a program in execution. Components: text (code), program counter, CPU registers, stack (local variables, return addresses), heap (dynamic memory), and data section (global variables).",
  },
  {
    id: "sa7",
    unit: 2,
    question: "Draw/describe the five process states.",
    answer:
      "New (being created), Ready (in memory, waiting for the CPU), Running (executing on the CPU), Waiting/Blocked (waiting for an event like I/O), and Terminated (finished). Transitions: New→Ready→Running→Terminated, with Running↔Waiting for I/O.",
  },
  {
    id: "sa8",
    unit: 2,
    question: "What is context switching and why is it overhead?",
    answer:
      "A context switch saves the current process's state to its PCB and loads the next process's state so it can resume later. It is overhead because the CPU does no useful work during the switch — frequent switching reduces performance.",
  },
  {
    id: "sa9",
    unit: 2,
    question: "Compare shared memory and message passing IPC.",
    answer:
      "Shared memory: processes share a region of memory — fast, but the programmer must handle synchronization. Message passing: the kernel moves messages between processes — easier and safer for small data, but slower due to kernel involvement.",
  },
  {
    id: "sa10",
    unit: 2,
    question: "Differentiate between a process and a thread.",
    answer:
      "A process is an independent program in execution with its own address space; a thread is a lightweight unit of execution within a process. Threads of the same process share code, data, and resources but each has its own stack, registers, and program counter, making threads cheaper to create and switch.",
  },
  {
    id: "sa11",
    unit: 3,
    question: "Explain the difference between preemptive and non-preemptive scheduling with one example each.",
    answer:
      "Non-preemptive: once a process gets the CPU it keeps it until it finishes or blocks (e.g. FCFS). Preemptive: the OS can interrupt a running process to give the CPU to another (e.g. Round Robin or SRTF). Preemptive needs a timer interrupt and gives better responsiveness.",
  },
  {
    id: "sa12",
    unit: 3,
    question: "Describe the convoy effect and which algorithm suffers from it.",
    answer:
      "The convoy effect occurs when short processes wait behind a long process, increasing average waiting time. FCFS suffers from it because the first (possibly long) arrival holds the CPU while others wait.",
  },
  {
    id: "sa13",
    unit: 3,
    question: "How does Round Robin solve starvation, and what is the time-quantum trade-off?",
    answer:
      "RR cycles through the ready queue giving each process a fixed quantum, so every process eventually runs (no starvation). Trade-off: too large a quantum degrades to FCFS (poor response); too small a quantum causes excessive context-switch overhead.",
  },
  {
    id: "sa14",
    unit: 3,
    question: "Explain how aging solves starvation in priority scheduling.",
    answer:
      "Aging gradually increases the priority of processes that have waited a long time. Eventually a long-waiting low-priority process becomes high priority and is scheduled, preventing indefinite starvation.",
  },
  {
    id: "sa15",
    unit: 3,
    question: "Define waiting time, turnaround time, and response time.",
    answer:
      "Waiting time = total time spent in the ready queue. Turnaround time = completion time − arrival time (total time in the system). Response time = time from arrival to the first moment the process gets the CPU.",
  },
  {
    id: "sa16",
    unit: 4,
    question: "List the requirements for a correct critical-section solution.",
    answer:
      "Mutual Exclusion (only one process in its critical section at a time), Progress (selection of the next process to enter cannot be postponed indefinitely), and Bounded Waiting (a limit on how long a process waits to enter).",
  },
  {
    id: "sa17",
    unit: 4,
    question: "State the four Coffman conditions for deadlock.",
    answer:
      "Mutual Exclusion (resources can't be shared), Hold and Wait (a process holds resources while requesting more), No Preemption (resources can't be forcibly taken), and Circular Wait (a circular chain of processes each waiting on the next).",
  },
  {
    id: "sa18",
    unit: 4,
    question: "Differentiate between a semaphore and a mutex.",
    answer:
      "A mutex is a locking mechanism allowing one thread in the critical section (lock/unlock), often causing busy waiting. A semaphore is an integer with atomic wait/signal operations; binary semaphores act like mutexes and counting semaphores manage multiple resources, and they block rather than busy-wait.",
  },
  {
    id: "sa19",
    unit: 4,
    question: "Explain the difference between deadlock prevention and deadlock avoidance.",
    answer:
      "Prevention ensures at least one of the four Coffman conditions can never hold (e.g. ordering resources to remove circular wait). Avoidance allows the conditions but uses information about future needs to grant requests only when the system stays in a safe state (e.g. Banker's Algorithm).",
  },
  {
    id: "sa20",
    unit: 4,
    question: "What is a race condition? Give a brief example.",
    answer:
      "A race condition occurs when multiple processes access shared data concurrently and the final result depends on the order of execution. Example: two threads both read a shared counter = 5, each add 1, and write back 6 — one update is lost instead of producing 7.",
  },
  {
    id: "sa21",
    unit: 5,
    question: "Differentiate between internal and external fragmentation.",
    answer:
      "Internal fragmentation: allocated memory is slightly larger than requested, wasting space inside a block (e.g. the last page frame). External fragmentation: total free memory is enough but it is scattered in small non-contiguous holes, so large requests can't be satisfied.",
  },
  {
    id: "sa22",
    unit: 5,
    question: "What is virtual memory and why is it important?",
    answer:
      "Virtual memory lets a process execute even when it is larger than physical memory by keeping parts on disk and loading them on demand. It enables larger programs, higher multiprogramming, process isolation, and efficient memory use.",
  },
  {
    id: "sa23",
    unit: 5,
    question: "Describe how demand paging works and define a page fault.",
    answer:
      "Demand paging loads a page into memory only when it is referenced. A page fault occurs when a referenced page is not in memory: the OS traps, loads the page from secondary storage (replacing one if memory is full), updates the page table, and resumes the process.",
  },
  {
    id: "sa24",
    unit: 5,
    question: "What is thrashing and how can it be controlled?",
    answer:
      "Thrashing is when a process spends more time paging than executing because it has too few frames, causing constant page faults and low CPU utilization. It is controlled using the working-set model or page-fault-frequency control to give each process enough frames, and by reducing the degree of multiprogramming.",
  },
  {
    id: "sa25",
    unit: 5,
    question: "Compare paging and segmentation.",
    answer:
      "Paging divides memory into fixed-size pages/frames; it eliminates external fragmentation but causes internal fragmentation and uses a page table. Segmentation divides a process into variable-sized logical segments (code, stack, data) matching the program's structure; it avoids internal fragmentation but can cause external fragmentation and uses a segment table.",
  },
  {
    id: "sa26",
    unit: 6,
    question: "Compare contiguous and indexed file allocation.",
    answer:
      "Contiguous allocation stores a file in consecutive blocks — fast sequential and direct access but causes external fragmentation and is hard to grow. Indexed allocation uses an index block holding pointers to all file blocks — supports direct access and avoids external fragmentation but adds index-block overhead.",
  },
  {
    id: "sa27",
    unit: 6,
    question: "Explain the components of disk access time.",
    answer:
      "Seek time: time to move the read/write head to the correct track. Rotational latency: time for the desired sector to rotate under the head. Transfer time: time to read/write the data. Total access time = seek time + rotational latency + transfer time.",
  },
  {
    id: "sa28",
    unit: 6,
    question: "Describe the SCAN (elevator) disk scheduling algorithm.",
    answer:
      "SCAN moves the disk head in one direction, servicing all requests until it reaches the end of the disk, then reverses direction and services requests on the way back — like an elevator. It gives more uniform wait times than SSTF and avoids starvation.",
  },
  {
    id: "sa29",
    unit: 6,
    question: "What is the purpose of a directory in a file system?",
    answer:
      "A directory is a structure that maps file names to their metadata and locations on disk. It organizes files (e.g. in a tree), supports operations like create, delete, search, list, and rename, and lets users group and locate files efficiently.",
  },
  {
    id: "sa30",
    unit: 7,
    question: "Explain the difference between buffering and caching in I/O, with an example of each.",
    answer:
      "Buffering temporarily holds data in transit to smooth speed or size mismatches (e.g. a disk-read buffer filled by DMA while the process consumes a previous one). Caching keeps copies of frequently accessed data for future reuse (e.g. the page cache that serves repeated file reads without going to disk).",
  },
  {
    id: "sa31",
    unit: 7,
    question: "What is DMA and how does it improve I/O performance?",
    answer:
      "Direct Memory Access lets a DMA controller transfer data directly between a device and memory without the CPU handling each byte. The CPU only sets up the transfer and is interrupted once when it completes, freeing it to do other work and greatly improving throughput for large transfers.",
  },
  {
    id: "sa32",
    unit: 7,
    question: "Compare programmed I/O, interrupt-driven I/O, and DMA.",
    answer:
      "Programmed I/O: the CPU polls the device status in a loop, wasting cycles. Interrupt-driven I/O: the device interrupts the CPU when ready, so the CPU isn't busy-waiting but still handles each data unit. DMA: a controller moves whole blocks between device and memory, interrupting the CPU only once at the end — best for large transfers.",
  },
  {
    id: "sa33",
    unit: 7,
    question: "What is the role of a device driver?",
    answer:
      "A device driver is kernel software that provides a uniform interface to the OS for a particular hardware device. It hides device-specific details, translates generic I/O requests into device commands, and handles the device's interrupts.",
  },
]
